INSERT INTO Department (Deptcode, Deptlocation) VALUES ('10J', 'Texas');
INSERT INTO Department (Deptcode, Deptlocation) VALUES ('11K', 'North Carolina');
INSERT INTO Department (Deptcode, Deptlocation) VALUES ('21U', 'Florida');
INSERT INTO Department (Deptcode, Deptlocation) VALUES ('8H', 'Manitoba');
INSERT INTO Department (Deptcode, Deptlocation) VALUES ('13M', 'Arizona');
INSERT INTO Department (Deptcode, Deptlocation) VALUES ('1A', 'Newfoundland');
INSERT INTO Department (Deptcode, Deptlocation) VALUES ('5E', 'New Brunswick');
INSERT INTO Department (Deptcode, Deptlocation) VALUES ('15O', 'Illinois');
INSERT INTO Department (Deptcode, Deptlocation) VALUES ('2B', 'Labrador');
INSERT INTO Department (Deptcode, Deptlocation) VALUES ('28BB', 'Virginia');
INSERT INTO Department (Deptcode, Deptlocation) VALUES ('24X', 'Washington');
INSERT INTO Department (Deptcode, Deptlocation) VALUES ('30DD', 'Ontario');
INSERT INTO Department (Deptcode, Deptlocation) VALUES ('29CC', 'Quebec');
INSERT INTO Department (Deptcode, Deptlocation) VALUES ('10J', 'Connecticut');
INSERT INTO Department (Deptcode, Deptlocation) VALUES ('14N', 'Nunavut');
INSERT INTO Department (Deptcode, Deptlocation) VALUES ('22V', 'Alabama');
INSERT INTO Department (Deptcode, Deptlocation) VALUES ('18R', 'Missouri');
INSERT INTO Department (Deptcode, Deptlocation) VALUES ('19S', 'Yukon');
INSERT INTO Department (Deptcode, Deptlocation) VALUES ('9I', 'New York');
INSERT INTO Department (Deptcode, Deptlocation) VALUES ('27AA', 'Pennsylvania');
INSERT INTO Department (Deptcode, Deptlocation) VALUES ('4D', 'California');
INSERT INTO Department (Deptcode, Deptlocation) VALUES ('6F', 'Oregon');
INSERT INTO Department (Deptcode, Deptlocation) VALUES ('7G', 'Utah');
INSERT INTO Department (Deptcode, Deptlocation) VALUES ('12L', 'Nevada');
INSERT INTO Department (Deptcode, Deptlocation) VALUES ('16P', 'Kansas');
INSERT INTO Department (Deptcode, Deptlocation) VALUES ('17Q', 'Nebraska');
INSERT INTO Department (Deptcode, Deptlocation) VALUES ('20T', 'Oklahoma');
INSERT INTO Department (Deptcode, Deptlocation) VALUES ('23W', 'Mississippi');
INSERT INTO Department (Deptcode, Deptlocation) VALUES ('25Y', 'Maryland');
INSERT INTO Department (Deptcode, Deptlocation) VALUES ('26Z', 'Delaware');
INSERT INTO Department (Deptcode, Deptlocation) VALUES ('27AA', 'Pennsylvania');
