INSERT INTO Job (job_id, jobName) VALUES (30, 'Research Nurse');
INSERT INTO Job (job_id, jobName) VALUES (28, 'Design Engineer');
INSERT INTO Job (job_id, jobName) VALUES (19, 'VP Product Management');
INSERT INTO Job (job_id, jobName) VALUES (1, 'Cost Accountant');
INSERT INTO Job (job_id, jobName) VALUES (7, 'Librarian'); 
INSERT INTO Job (job_id, jobName) VALUES (14, 'Analog Circuit Design Manager');
INSERT INTO Job (job_id, jobName) VALUES (13, 'Recruiting Manager');
INSERT INTO Job (job_id, jobName) VALUES (6, 'Graphic Designer');
INSERT INTO Job (job_id, jobName) VALUES (10, 'Administrative Assistant II');
INSERT INTO Job (job_id, jobName) VALUES (8, 'Sales Associate');
INSERT INTO Job (job_id, jobName) VALUES (4, 'Chemical Engineer');
INSERT INTO Job (job_id, jobName) VALUES (27, 'Assistant Media Planner');
INSERT INTO Job (job_id, jobName) VALUES (22, 'Developer IV');
INSERT INTO Job (job_id, jobName) VALUES (26, 'Automation Specialist II');
INSERT INTO Job (job_id, jobName) VALUES (12, 'Senior Editor');
INSERT INTO Job (job_id, jobName) VALUES (17, 'Payment Adjustment Coordinator');
INSERT INTO Job (job_id, jobName) VALUES (25, 'Help Desk Operator');
INSERT INTO Job (job_id, jobName) VALUES (2, 'System Analyst');
INSERT INTO Job (job_id, jobName) VALUES (3, 'Software Engineer');
INSERT INTO Job (job_id, jobName) VALUES (7, 'Database Administrator');
INSERT INTO Job (job_id, jobName) VALUES (9, 'Project Coordinator');
INSERT INTO Job (job_id, jobName) VALUES (11, 'Marketing Assistant');
INSERT INTO Job (job_id, jobName) VALUES (15, 'Human Resources Specialist');
INSERT INTO Job (job_id, jobName) VALUES (16, 'Financial Manager');
INSERT INTO Job (job_id, jobName) VALUES (18, 'Customer Service Rep');
INSERT INTO Job (job_id, jobName) VALUES (20, 'Safety Inspector');
INSERT INTO Job (job_id, jobName) VALUES (21, 'Electrician');
INSERT INTO Job (job_id, jobName) VALUES (23, 'Chef');
INSERT INTO Job (job_id, jobName) VALUES (24, 'Security Guard');
INSERT INTO Job (job_id, jobName) VALUES (29, 'Pilot');